apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
secretGenerator:
  - name: ssslite-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/ssslite
    newTag: 1.0.5
