apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssslite-deployment
  labels:
    app: ssslite-deployment
spec:
  selector:
    matchLabels:
      app: ssslite-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssslite-deployment
    spec:
      containers:
        - name: ssslite
          image: ghcr.io/dbca-wa/ssslite
          imagePullPolicy: Always
          env:
            - name: TZ
              value: 'Australia/Perth'
          resources:
            requests:
              memory: '64Mi'
              cpu: '5m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          startupProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: 'Memory'
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
      tolerations:
        - key: arch
          operator: Equal
          value: arm64
          effect: NoSchedule
